In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [34]:
import pandas as pd
import numpy as np

dictionary =  {'A' : [1000, 200, 3, 14], 'B' : [400, np.nan, 2, 105], 'c' :[5000, 3,100, 1000], 'd' :['gh', 'jo', np.nan, 'dd']}

In [35]:
dictionary

{'A': [1000, 200, 3, 14],
 'B': [400, nan, 2, 105],
 'c': [5000, 3, 100, 1000],
 'd': ['gh', 'jo', nan, 'dd']}

In [36]:
df_dictionary= pd.DataFrame(dictionary)
df_dictionary

A      B     c    d
0  1000  400.0  5000   gh
1   200    NaN     3   jo
2     3    2.0   100  NaN
3    14  105.0  1000   dd

In [38]:
########## get numeric data
df_dictionary = df_dictionary.select_dtypes(exclude=['object'])
# Or >>> df_dictionary = df_dictionary.select_dtypes(include=[np.number])

df_dictionary

A      B     c
0  1000  400.0  5000
1   200    NaN     3
2     3    2.0   100
3    14  105.0  1000

In [32]:
col=df_dictionary.columns
col

Index(['A', 'B', 'c'], dtype='object')

In [39]:
######### Normalizer does not work with missing values
from sklearn.impute import SimpleImputer
imp= SimpleImputer(missing_values=np.nan, strategy='mean')
imp = imp.fit(df_dictionary)
norm_dictionary = imp.transform(df_dictionary)
norm_dictionary

array([[1.00e+03, 4.00e+02, 5.00e+03],
       [2.00e+02, 1.69e+02, 3.00e+00],
       [3.00e+00, 2.00e+00, 1.00e+02],
       [1.40e+01, 1.05e+02, 1.00e+03]])

In [40]:
from sklearn.preprocessing import Normalizer 
scaler = Normalizer(norm='l2') # you can change the norm to 'l1' or 'max' 
scale_dictionary = scaler.fit_transform(norm_dictionary)
scale_dictionary

array([[0.19551547, 0.07820619, 0.97757736],
       [0.76377057, 0.64538613, 0.01145656],
       [0.02998052, 0.01998701, 0.99935063],
       [0.01392211, 0.10441581, 0.99443628]])

In [41]:
scale_dictionary= pd.DataFrame(scale_dictionary)
scale_dictionary

0         1         2
0  0.195515  0.078206  0.977577
1  0.763771  0.645386  0.011457
2  0.029981  0.019987  0.999351
3  0.013922  0.104416  0.994436

In [43]:
scale_dictionary.columns=df_dictionary.columns
scale_dictionary

A         B         c
0  0.195515  0.078206  0.977577
1  0.763771  0.645386  0.011457
2  0.029981  0.019987  0.999351
3  0.013922  0.104416  0.994436

# **Example**

In [51]:
data=pd.read_csv('/content/drive/MyDrive/sklearn/cleaning/Marketting.csv')

In [52]:
data.shape

(30471, 292)

In [53]:
data= data.select_dtypes(include=[np.number]) # Normalizer does not work with missing values
print(data.shape)
data.head(3)

(30471, 276)


id  full_sq  life_sq  ...  sport_count_5000  market_count_5000  price_doc
0   1       43     27.0  ...                52                  4    5850000
1   2       34     19.0  ...                66                 14    6000000
2   3       43     29.0  ...                67                 10    5700000

[3 rows x 276 columns]

In [54]:
data= data.drop(['id'], axis=1)
print(data.shape)
data.head(2)

(30471, 275)


full_sq  life_sq  floor  ...  sport_count_5000  market_count_5000  price_doc
0       43     27.0    4.0  ...                52                  4    5850000
1       34     19.0    3.0  ...                66                 14    6000000

[2 rows x 275 columns]

In [64]:
data= data[data.isnull().sum(axis=1)<10]  # remove all rows having nan's > 10
data= data[data.columns[data.isnull().sum() < 20]] # remove all coulmns having nan's > 20
print(data.shape)

(25657, 231)


In [67]:
from sklearn.impute import SimpleImputer
imp= SimpleImputer (missing_values=np.nan, strategy='mean')
imp= imp.fit(data)
data_imp= imp.transform(data)
data_imp= pd.DataFrame(data_imp)
data_imp.head()

0             1         2         3    ...   227    228   229         230
0  43.0  6.407578e+06  155572.0  0.189727  ...   0.0   52.0   4.0   5850000.0
1  34.0  9.589337e+06  115352.0  0.372602  ...  10.0   66.0  14.0   6000000.0
2  43.0  4.808270e+06  101708.0  0.112560  ...   4.0   67.0  10.0   5700000.0
3  89.0  1.258354e+07  178473.0  0.194703  ...   0.0   26.0   3.0  13100000.0
4  77.0  8.398461e+06  108171.0  0.015234  ...  91.0  195.0  14.0  16331452.0

[5 rows x 231 columns]

In [68]:
'''
    from sklearn.preprocessing import StandardScaler 
    scaler = StandardScaler()
    scaler.fit(data)
    newdata = scaler.transform(data)
                                                   or
                                                      from sklearn.preprocessing import MinMaxScaler
                                                      scaler = MinMaxScaler()
                                                      scaler.fit(data)
                                                      newdata = scaler.transform(data)

''' 
from sklearn.preprocessing import Normalizer 
scaler = Normalizer(norm='l2') # you can change the norm to 'l1' or 'max' 
scale_data = scaler.fit_transform(data_imp)
scale_data

array([[4.38916229e-06, 6.54044190e-01, 1.58797850e-02, ...,
        5.30782417e-06, 4.08294167e-07, 5.97130219e-01],
       [2.86955727e-06, 8.09327985e-01, 9.73556384e-03, ...,
        5.57031706e-06, 1.18158241e-06, 5.06392460e-01],
       [5.53602076e-06, 6.19039108e-01, 1.30943628e-02, ...,
        8.62589282e-06, 1.28744669e-06, 7.33844613e-01],
       ...,
       [2.99535369e-06, 2.54514875e-01, 2.62535785e-03, ...,
        5.95587768e-06, 5.22445411e-07, 8.70742352e-01],
       [4.28565460e-06, 4.05132610e-01, 5.26439097e-03, ...,
        4.35261796e-06, 4.68743472e-07, 9.04005268e-01],
       [5.98787826e-06, 6.12063201e-01, 1.31679013e-02, ...,
        7.51966108e-06, 1.39252983e-06, 7.79816704e-01]])

In [71]:
scale_data= pd.DataFrame(scale_data)
scale_data.columns= data.columns
scale_data.head(3)

full_sq    area_m  ...  market_count_5000  price_doc
0  0.000004  0.654044  ...       4.082942e-07   0.597130
1  0.000003  0.809328  ...       1.181582e-06   0.506392
2  0.000006  0.619039  ...       1.287447e-06   0.733845

[3 rows x 231 columns]