In [1]:
from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


# **train_test_split**

In [20]:
from sklearn.datasets import load_breast_cancer
import pandas as pd

In [21]:
Data= load_breast_cancer()
X= Data.data
y= Data.target
print(X.shape)



(569, 30)


In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.3, random_state=44, shuffle=True)

In [23]:
print('X_train shape is ' , X_train.shape)
print('X_test shape is ' , X_test.shape)
print('y_train shape is ' , y_train.shape)
print('y_test shape is ' , y_test.shape)


X_train shape is  (398, 30)
X_test shape is  (171, 30)
y_train shape is  (398,)
y_test shape is  (171,)


# **K_FOLDE**

In [33]:
import numpy as np
from sklearn.model_selection import KFold

X = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
y = np.array([11, 22, 33, 44])

#nn = 2
#nn=3
nn=4

kf =  KFold(n_splits=nn, random_state=None, shuffle=False)
#kf.get_n_splits(X)
print(X)
print(y)
for train_index, test_index in kf.split(X):
    print("\n TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print('X_train \n' , X_train)
    print('X_test \n' , X_test)
    print('y_train \n' ,y_train)
    print('y_test \n' , y_test)




[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[11 22 33 44]

 TRAIN: [1 2 3] TEST: [0]
X_train 
 [[3 4]
 [5 6]
 [7 8]]
X_test 
 [[1 2]]
y_train 
 [22 33 44]
y_test 
 [11]

 TRAIN: [0 2 3] TEST: [1]
X_train 
 [[1 2]
 [5 6]
 [7 8]]
X_test 
 [[3 4]]
y_train 
 [11 33 44]
y_test 
 [22]

 TRAIN: [0 1 3] TEST: [2]
X_train 
 [[1 2]
 [3 4]
 [7 8]]
X_test 
 [[5 6]]
y_train 
 [11 22 44]
y_test 
 [33]

 TRAIN: [0 1 2] TEST: [3]
X_train 
 [[1 2]
 [3 4]
 [5 6]]
X_test 
 [[7 8]]
y_train 
 [11 22 33]
y_test 
 [44]


# **Leave One Out**

In [38]:
import numpy as np
from sklearn.model_selection import LeaveOneOut

X = np.array([1, 2, 3, 4])
y = np.array([5,6,7,8])

loo = LeaveOneOut()
#loo.get_n_splits(X)

LeaveOneOut()
for train_index, test_index in loo.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print('X_train \n' , X_train)
    print('X_test \n' , X_test)
    print('y_train \n' ,y_train)
    print('y_test \n' , y_test)


TRAIN: [1 2 3] TEST: [0]
X_train 
 [2 3 4]
X_test 
 [1]
y_train 
 [6 7 8]
y_test 
 [5]
TRAIN: [0 2 3] TEST: [1]
X_train 
 [1 3 4]
X_test 
 [2]
y_train 
 [5 7 8]
y_test 
 [6]
TRAIN: [0 1 3] TEST: [2]
X_train 
 [1 2 4]
X_test 
 [3]
y_train 
 [5 6 8]
y_test 
 [7]
TRAIN: [0 1 2] TEST: [3]
X_train 
 [1 2 3]
X_test 
 [4]
y_train 
 [5 6 7]
y_test 
 [8]
