In [4]:
from google.colab import drive
drive.mount("/content/drive", force_remount=True)

Mounted at /content/drive


# **linear_model import LinearRegression**

In [7]:
from sklearn.datasets import load_boston
dataset= load_boston()
features= dataset.data
targets= dataset.target


/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i.e.

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(features,targets,test_size=0.3, random_state= 44, shuffle= True)
print('X_train is ',X_train.shape)
print('X_test is ',X_test.shape)
print('y_train is ',y_train.shape)
print('y_test is ',y_test.shape)

X_train is  (354, 13)
X_test is  (152, 13)
y_train is  (354,)
y_test is  (152,)


In [9]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression(fit_intercept=True, normalize=True,copy_X=True,n_jobs=-1)
 # fit_intercept :حساب قيمة التقاطع مع محور اكس
lr.fit(X_train, y_train)
print(lr.score(X_train, y_train),'\n')
print(lr.score(X_test, y_test),'\n')
y_pred= lr.predict(X_test)
print('======================')
print('y_pred is', y_pred.shape)
print(y_pred[:5])
print('======================')
print(y_test[:5])

0.7293698153057147 

0.7532417995961491 

y_pred is (152,)
[17.72068078 25.18230573 21.70246845 36.15306445 13.73291424]
[17.8 21.5 21.2 32.4 10.9]


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_base.py:145: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)


  FutureWarning,


In [10]:
from sklearn.metrics import mean_absolute_error
error= mean_absolute_error(y_test,y_pred,multioutput='uniform_average') 
print(error)

3.43186932227615


# **Ridge Regression**

In [17]:
from sklearn.linear_model import Ridge
LRridge= Ridge(alpha=0.2,random_state= 33)
LRridge.fit(X_train, y_train)
print(LRridge.score(X_train,y_train))
print(LRridge.score(X_test,y_test))
y_pred=LRridge.predict(X_test)
print('======================')
print(y_pred[:5])
print('======================')
print(y_test[:5])

0.7289646521093622
0.7548537221289422
[17.70402127 24.910565   21.64115818 36.03033479 13.86051403]
[17.8 21.5 21.2 32.4 10.9]


# **Lasso Regression**

In [21]:
from sklearn.linear_model import Lasso
Lrlasso= Lasso(alpha=0.005, random_state=33)
Lrlasso.fit(X_train, y_train)
print(Lrlasso.score(X_train,y_train))
print(Lrlasso.score(X_test,y_test))
y_pred=Lrlasso.predict(X_test)
print('======================')
print(y_pred[:5])
print('======================')
print(y_test[:5])

0.729253113419801
0.7540583518179096
[17.71758767 24.98471389 21.67649007 36.02473692 13.80507148]
[17.8 21.5 21.2 32.4 10.9]


# **SGD Regressor**

In [29]:
from sklearn.linear_model import SGDRegressor
SGDRegression = SGDRegressor(alpha=0.006,random_state=33,penalty='l1',loss = 'huber')
SGDRegression.fit(X_train, y_train)
print(SGDRegression.score(X_train,y_train))
print(SGDRegression.score(X_test,y_test))
y_pred=SGDRegression.predict(X_test)
print('======================')
print(y_pred[:5])
print('======================')
print(y_test[:5])

0.3303062635314903
0.29374664789278493
[19.46739518 20.59365889 19.35490074 25.73236676  5.48123201]
[17.8 21.5 21.2 32.4 10.9]


# **Example with one variable**

In [30]:
import numpy as np

X = np.array([[1, 1], [1, 2], [2, 2], [2, 3]])

y = np.dot(X, np.array([1, 2])) + 3  # y = 1 * x_0 + 2 * x_1 + 3
print(X,'\n',y)


[[1 1]
 [1 2]
 [2 2]
 [2 3]] 
 [ 6  8  9 11]


In [31]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression(fit_intercept=True, normalize=True)
lr.fit(X,y)
y_pred=lr.predict(np.array([[3, 3]]))
print(y_pred)

[12.]


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_base.py:145: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)


  FutureWarning,
